FROM node:22-alpine AS build
RUN npm install -g pnpm
WORKDIR /app
COPY pnpm-lock.yaml pnpm-workspace.yaml* package.json ./
COPY client/package.json ./client/
RUN pnpm install --frozen-lockfile --filter client
COPY . .
RUN pnpm --filter client run build

FROM nginx:stable-alpine
COPY --from=build /app/client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]